export const strings = {
  login: {
    title: "Sign In to The App",
    emailLabel: "E-mail",
    emailPlaceholder: "test@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "**********",
    rememberMe: "Remember me",
    signInButton: "Sign In",
    noAccount: "Don't have an account?",
    signUpLink: "Sign up",
  },
  signup: {
    title: "Sign Up",
    emailLabel: "E-mail",
    emailPlaceholder: "test@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "**********",
    confirmPasswordLabel: "Confirm Password",
    confirmPasswordPlaceholder: "**********",
    signUpButton: "Sign Up",
    haveAccount: "Already have an account?",
    signInLink: "Sign in",
  },
  home: {
    title: "User Activity",
    blockButton: "Block",
    unblockButton: "Unblock",
    deleteButton: "Delete",
    filterPlaceholder: "Filter",
    tableHeaders: {
      email: "Email",
      lastSeen: "Last Seen",
      name: "Name",
      role: "Role",
      status: "Status",
    },
  },
};
